config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.cern.ch/corryvreckan/corryvreckan:
      branch: master
      repo: https://gitlab.cern.ch/corryvreckan/corryvreckan/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.cern.ch/corryvreckan/corryvreckan git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cornflower-zonkey.sh
        container: qc.acc_jumpy-russet-reindeer
  QC.Doc:
    repos:
      gitlab.cern.ch/corryvreckan/corryvreckan find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-wheat-setter.sh
        container: qc.doc_gamy-violet-schnauzer
      gitlab.cern.ch/corryvreckan/corryvreckan git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-aquamarine-mule.sh
        container: qc.doc_greasy-chestnut-oriole
      gitlab.cern.ch/corryvreckan/corryvreckan markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-linen-jellyfish.sh
        container: qc.doc_crabby-green-cassowary
  QC.Lic:
    repos:
      gitlab.cern.ch/corryvreckan/corryvreckan licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-amaranth-drever.sh
        container: qc.lic_seedy-goldenrod-beagle
  QC.Sec:
    repos:
      gitlab.cern.ch/corryvreckan/corryvreckan bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-aquamarine-uakari.sh
        container: qc.sec_squeaky-seashell-grouse
  QC.Sty:
    repos:
      gitlab.cern.ch/corryvreckan/corryvreckan flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-copper-civet.sh
        container: qc.sty_shaggy-ecru-zorse
      gitlab.cern.ch/corryvreckan/corryvreckan hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-mauve-drever.sh
        container: qc.sty_boozy-ochre-burmese
  QC.Ver:
    repos:
      gitlab.cern.ch/corryvreckan/corryvreckan get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-gold-gibbon.sh
        container: qc.ver_muzzy-celadon-caterpillar
timeout: 5400
