config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bcobo/SIRENA:
      branch: master
      repo: https://github.com/bcobo/SIRENA/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bcobo/SIRENA git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-magenta-capuchin.sh
        container: qc.acc_muggy-carmine-ibis
  QC.Doc:
    repos:
      github.com/bcobo/SIRENA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-seashell-retriever.sh
        container: qc.doc_pokey-persimmon-chin
      github.com/bcobo/SIRENA git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-salmon-coyote.sh
        container: qc.doc_nerdy-teal-hare
      github.com/bcobo/SIRENA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-mustard-seal.sh
        container: qc.doc_chewy-turquoise-millipede
      github.com/bcobo/SIRENA restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-russet-markhor.sh
        container: qc.doc_breezy-cardinal-bison
  QC.Lic:
    repos:
      github.com/bcobo/SIRENA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-pear-falcon.sh
        container: qc.lic_trippy-viridian-bear
  QC.Sec:
    repos:
      github.com/bcobo/SIRENA bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-blue-dhole.sh
        container: qc.sec_snazzy-azure-insect
  QC.Sty:
    repos:
      github.com/bcobo/SIRENA flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-copper-kiwi.sh
        container: qc.sty_silly-ruby-armadillo
      github.com/bcobo/SIRENA jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-burgundy-mandrill.sh
        container: qc.sty_lumpy-fuchsia-fly
  QC.Uni:
    repos:
      github.com/bcobo/SIRENA pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-maroon-armadillo.sh
        container: qc.uni_homely-plum-olm
  QC.Ver:
    repos:
      github.com/bcobo/SIRENA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-auburn-stingray.sh
        container: qc.ver_boozy-linen-mau
timeout: 5400
