config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-white-newfoundland.sh
        container: qc.acc_paltry-burgundy-wolverine
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-white-chicken.sh
        container: qc.doc_wiggy-tan-ibis
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-amaranth-flamingo.sh
        container: qc.doc_cheeky-violet-lynx
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-blue-rottweiler.sh
        container: qc.doc_greasy-burgundy-gerbil
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-burgundy-blue.sh
        container: qc.lic_lousy-persimmon-hyrax
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-zucchini-moose.sh
        container: qc.sec_snippy-firebrick-jaguar
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-tomato-seal.sh
        container: qc.sty_lanky-ultramarine-eel
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-black-fossa.sh
        container: qc.ver_ready-black-seal
timeout: 5400
