config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.inf.unibz.it/earth_observation_public/raster-to-stac:
      branch: main
      repo: https://gitlab.inf.unibz.it/earth_observation_public/raster-to-stac/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-crimson-fox.sh
        container: qc.acc_gummy-myrtle-dhole
  QC.Doc:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cobalt-paradise.sh
        container: qc.doc_skimpy-saffron-chinook
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-bronze-tang.sh
        container: qc.doc_leaky-cerise-buffalo
  QC.Lic:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-silver-coati.sh
        container: qc.lic_droopy-vermilion-kangaroo
  QC.Ver:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-sangria-drever.sh
        container: qc.ver_muzzy-cinnabar-robin
timeout: 5400
