config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rizac/stream2segment:
      branch: main
      repo: https://github.com/rizac/stream2segment/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rizac/stream2segment git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-mustard-akbash.sh
        container: qc.acc_queasy-corn-bison
  QC.Doc:
    repos:
      github.com/rizac/stream2segment find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-lilac-tuatara.sh
        container: qc.doc_slimy-apricot-alligator
      github.com/rizac/stream2segment git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-bronze-alligator.sh
        container: qc.doc_seedy-wisteria-donkey
      github.com/rizac/stream2segment markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-sepia-harrier.sh
        container: qc.doc_frumpy-cream-retriever
  QC.Lic:
    repos:
      github.com/rizac/stream2segment licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-green-tetra.sh
        container: qc.lic_sleazy-tangerine-toucan
  QC.Sec:
    repos:
      github.com/rizac/stream2segment bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-thistle-numbat.sh
        container: qc.sec_tacky-purple-monkey
  QC.Sty:
    repos:
      github.com/rizac/stream2segment flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-crimson-terrier.sh
        container: qc.sty_droopy-olive-heron
  QC.Uni:
    repos:
      github.com/rizac/stream2segment pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-green-bee.sh
        container: qc.uni_stuffy-cerise-bordeaux
  QC.Ver:
    repos:
      github.com/rizac/stream2segment get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-olivine-mongrel.sh
        container: qc.ver_craggy-wisteria-macaque
timeout: 5400
