config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/dianagudu/motley_cue:
      branch: master
      repo: https://github.com/dianagudu/motley_cue/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/dianagudu/motley_cue git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-myrtle-hornet.sh
        container: qc.acc_bluesy-cornflower-caterpillar
  QC.Doc:
    repos:
      github.com/dianagudu/motley_cue find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-vermilion-nightingale.sh
        container: qc.doc_gloppy-linen-llama
      github.com/dianagudu/motley_cue git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-black-russel.sh
        container: qc.doc_skinny-lime-markhor
      github.com/dianagudu/motley_cue markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-beige-dhole.sh
        container: qc.doc_wiggy-flax-mayfly
      github.com/dianagudu/motley_cue restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-azure-lion.sh
        container: qc.doc_randy-teal-barb
  QC.Lic:
    repos:
      github.com/dianagudu/motley_cue licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-aqua-mammoth.sh
        container: qc.lic_snazzy-azure-barracuda
  QC.Sec:
    repos:
      github.com/dianagudu/motley_cue bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-seashell-corgi.sh
        container: qc.sec_nerdy-mauve-chameleon
  QC.Sty:
    repos:
      github.com/dianagudu/motley_cue flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-mauve-sheep.sh
        container: qc.sty_pretty-tan-chimpanzee
  QC.Ver:
    repos:
      github.com/dianagudu/motley_cue get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-orange-retriever.sh
        container: qc.ver_messy-lemon-dalmatian
timeout: 5400
