config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-tomato-termite.sh
        container: qc.acc_squirrely-taupe-newfoundland
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-amber-dane.sh
        container: qc.doc_snappy-orchid-anteater
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-plum-mongrel.sh
        container: qc.doc_squeaky-alizarin-flamingo
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lemon-tang.sh
        container: qc.doc_skinny-emerald-bullfrog
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-copper-numbat.sh
        container: qc.lic_pokey-periwinkle-reindeer
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-ivory-cow.sh
        container: qc.sec_shabby-gamboge-badger
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-dandelion-molly.sh
        container: qc.sty_bumpy-firebrick-harrier
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cornflower-fossa.sh
        container: qc.ver_baggy-chestnut-chipmunk
timeout: 5400
