config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-pink-centipede.sh
        container: qc.acc_jumpy-amber-jaguar
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-flax-wombat.sh
        container: qc.doc_crappy-xanthic-dalmatian
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-corn-terrier.sh
        container: qc.doc_greasy-chocolate-foxhound
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-linen-dhole.sh
        container: qc.doc_sleepy-silver-orangutan
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-azure-lemur.sh
        container: qc.lic_skimpy-ecru-jackal
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-tan-tarsier.sh
        container: qc.sec_shaky-fuchsia-lynx
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cyan-duck.sh
        container: qc.sty_pasty-crimson-okapi
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-chocolate-zonkey.sh
        container: qc.ver_sickly-cinnabar-moorhen
timeout: 5400
