config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/dCache/dcache:
      branch: master
      repo: https://github.com/dCache/dcache/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/dCache/dcache git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-dandelion-turkey.sh
        container: qc.acc_muzzy-dandelion-llama
  QC.Doc:
    repos:
      github.com/dCache/dcache find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-periwinkle-frigatebird.sh
        container: qc.doc_snippy-grey-dachshund
      github.com/dCache/dcache git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-amaranth-cassowary.sh
        container: qc.doc_whiny-heliotrope-loon
      github.com/dCache/dcache markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-pumpkin-angora.sh
        container: qc.doc_squirrely-ecru-macaw
  QC.Lic:
    repos:
      github.com/dCache/dcache licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-coral-flounder.sh
        container: qc.lic_craggy-taupe-quokka
  QC.Met:
    repos:
      github.com/dCache/dcache cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-vermilion-gecko.sh
        container: qc.met_lovely-mustard-cichlid
  QC.Sec:
    repos:
      github.com/dCache/dcache bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-carmine-sloth.sh
        container: qc.sec_dorky-periwinkle-orangutan
  QC.Sty:
    repos:
      github.com/dCache/dcache checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-mauve-squid.sh
        container: qc.sty_ugly-eggplant-hyena
      github.com/dCache/dcache flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cream-yak.sh
        container: qc.sty_cozy-brass-moth
      github.com/dCache/dcache hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-charcoal-grasshopper.sh
        container: qc.sty_queasy-purple-barnacle
      github.com/dCache/dcache jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-chocolate-burmese.sh
        container: qc.sty_craggy-pumpkin-snail
      github.com/dCache/dcache rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-magnolia-dachshund.sh
        container: qc.sty_sleazy-jade-kingfisher
  QC.Ver:
    repos:
      github.com/dCache/dcache get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-thistle-lemur.sh
        container: qc.ver_scanty-plum-lobster
timeout: 5400
