config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-compose:
      branch: main
      repo: https://github.com/ai4os/ai4-compose/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-pear-schnauzer.sh
        container: qc.acc_snoopy-ecru-snail
  QC.Doc:
    repos:
      github.com/ai4os/ai4-compose find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-azure-flamingo.sh
        container: qc.doc_snazzy-persimmon-wolf
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-red-elephant.sh
        container: qc.doc_randy-champagne-indri
  QC.Lic:
    repos:
      github.com/ai4os/ai4-compose licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-blue-mouse.sh
        container: qc.lic_skimpy-magnolia-mouse
  QC.Ver:
    repos:
      github.com/ai4os/ai4-compose get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-seashell-orangutan.sh
        container: qc.ver_surly-champagne-harrier
timeout: 5400
