config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/rcstar/openQxD:
      branch: master
      repo: https://gitlab.com/rcstar/openQxD/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/rcstar/openQxD git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-plum-bloodhound.sh
        container: qc.acc_sleepy-olivine-emu
  QC.Doc:
    repos:
      gitlab.com/rcstar/openQxD find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-chestnut-frigatebird.sh
        container: qc.doc_queasy-smalt-birman
      gitlab.com/rcstar/openQxD git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-aqua-hedgehog.sh
        container: qc.doc_clammy-olive-oyster
      gitlab.com/rcstar/openQxD markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-copper-grasshopper.sh
        container: qc.doc_flaky-sangria-malamute
  QC.Lic:
    repos:
      gitlab.com/rcstar/openQxD licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cerise-sponge.sh
        container: qc.lic_nippy-rust-greyhound
  QC.Ver:
    repos:
      gitlab.com/rcstar/openQxD get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-emerald-hummingbird.sh
        container: qc.ver_squeaky-coral-collie
timeout: 5400
