config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-orange-eel.sh
        container: qc.acc_sleepy-magenta-bullfrog
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cerise-eagle.sh
        container: qc.doc_pretty-charcoal-labradoodle
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-linen-rattlesnake.sh
        container: qc.doc_stinky-periwinkle-bonobo
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-sangria-cassowary.sh
        container: qc.doc_scaly-peach-wallaby
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-jade-chipmunk.sh
        container: qc.lic_skinny-champagne-swan
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cardinal-devil.sh
        container: qc.sec_messy-taupe-zebra
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-brass-bombay.sh
        container: qc.sty_fuzzy-corn-hyrax
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-auburn-ant.sh
        container: qc.ver_beady-saffron-dodo
timeout: 5400
