config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.inf.unibz.it/earth_observation_public/raster-to-stac:
      branch: main
      repo: https://gitlab.inf.unibz.it/earth_observation_public/raster-to-stac/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-green-buffalo.sh
        container: qc.acc_snazzy-cinnabar-cuttlefish
  QC.Doc:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-tangerine-gopher.sh
        container: qc.doc_tacky-plum-wrasse
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-beige-bombay.sh
        container: qc.doc_lanky-bronze-numbat
  QC.Lic:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-eggplant-beaver.sh
        container: qc.lic_snoopy-crimson-bandicoot
  QC.Ver:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-magenta-coati.sh
        container: qc.ver_dorky-orange-barracuda
timeout: 5400
