config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/mlflow-auth-gui:
      branch: main
      repo: https://github.com/m-team-kit/mlflow-auth-gui/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ruby-woodpecker.sh
        container: qc.acc_queasy-malachite-sheep
  QC.Doc:
    repos:
      github.com/m-team-kit/mlflow-auth-gui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cinnabar-dogfish.sh
        container: qc.doc_stealthy-olivine-wallaby
      github.com/m-team-kit/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-gamboge-burmese.sh
        container: qc.doc_homely-cream-ferret
  QC.Lic:
    repos:
      github.com/m-team-kit/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-coral-ladybird.sh
        container: qc.lic_flimsy-emerald-fossa
  QC.Ver:
    repos:
      github.com/m-team-kit/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-platinum-wombat.sh
        container: qc.ver_muggy-ruby-dingo
timeout: 5400
