config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-magnolia-serval.sh
        container: qc.acc_squeaky-teal-discus
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-copper-badger.sh
        container: qc.doc_grumpy-salmon-elephant
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-tomato-mau.sh
        container: qc.doc_slimy-eggplant-deer
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-teal-russel.sh
        container: qc.doc_lanky-lavender-dodo
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-sepia-russel.sh
        container: qc.lic_cheeky-sepia-bulldog
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-magnolia-caterpillar.sh
        container: qc.sec_droopy-rust-monster
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-khaki-barb.sh
        container: qc.sty_shabby-ochre-lobster
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-wheat-ladybird.sh
        container: qc.ver_paltry-sangria-cat
timeout: 5400
