config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/itwinai:
      branch: fix/sqaaas
      repo: https://github.com/interTwin-eu/itwinai/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/itwinai git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-persimmon-mammoth.sh
        container: qc.acc_goopy-green-bison
  QC.Doc:
    repos:
      github.com/interTwin-eu/itwinai find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-rose-chin.sh
        container: qc.doc_gloppy-grey-jellyfish
      github.com/interTwin-eu/itwinai git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-wheat-bordeaux.sh
        container: qc.doc_muggy-sapphire-angelfish
      github.com/interTwin-eu/itwinai markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-ultramarine-coati.sh
        container: qc.doc_gloppy-olive-cougar
      github.com/interTwin-eu/itwinai restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-smalt-hound.sh
        container: qc.doc_grumpy-lemon-greyhound
  QC.Lic:
    repos:
      github.com/interTwin-eu/itwinai licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-salmon-goose.sh
        container: qc.lic_snoopy-white-antelope
  QC.Sec:
    repos:
      github.com/interTwin-eu/itwinai bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-sepia-chimpanzee.sh
        container: qc.sec_scanty-magenta-toucan
  QC.Sty:
    repos:
      github.com/interTwin-eu/itwinai flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-razzmatazz-monkey.sh
        container: qc.sty_flabby-persimmon-tarsier
      github.com/interTwin-eu/itwinai hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-dandelion-coati.sh
        container: qc.sty_lovely-celadon-ant
      github.com/interTwin-eu/itwinai jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-salmon-elephant.sh
        container: qc.sty_sleepy-salmon-bison
  QC.Uni:
    repos:
      github.com/interTwin-eu/itwinai pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-amaranth-russel.sh
        container: qc.uni_crabby-alizarin-skunk
  QC.Ver:
    repos:
      github.com/interTwin-eu/itwinai get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-aqua-frigatebird.sh
        container: qc.ver_stinky-azure-owl
timeout: 5400
