config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.inf.unibz.it/earth_observation_public/raster-to-stac:
      branch: main
      repo: https://gitlab.inf.unibz.it/earth_observation_public/raster-to-stac/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-persimmon-tetra.sh
        container: qc.acc_gloppy-pear-dormouse
  QC.Doc:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-brass-quoll.sh
        container: qc.doc_lovely-jade-cougar
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-saffron-liger.sh
        container: qc.doc_squeaky-seashell-chow
  QC.Lic:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-grey-catfish.sh
        container: qc.lic_greasy-crimson-lynx
  QC.Ver:
    repos:
      gitlab.inf.unibz.it/earth_observation_public/raster-to-stac get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-rose-stingray.sh
        container: qc.ver_nippy-orange-bee
timeout: 5400
