config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject:
      branch: main
      repo: https://github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-plum-albatross.sh
        container: qc.acc_sleazy-cinnabar-slug
  QC.Doc:
    repos:
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-grey-kakapo.sh
        container: qc.doc_queasy-maroon-armadillo
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-buff-eleuth.sh
        container: qc.doc_woolly-corn-swan
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-celadon-ragdoll.sh
        container: qc.doc_shaky-zucchini-forest
  QC.Lic:
    repos:
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-ruby-wolfhound.sh
        container: qc.lic_chewy-silver-koala
  QC.Sec:
    repos:
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chocolate-worm.sh
        container: qc.sec_freaky-azure-dachsbracke
  QC.Sty:
    repos:
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-sepia-woodpecker.sh
        container: qc.sty_stinky-rose-maltese
  QC.Uni:
    repos:
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject pytest:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-lavender-angelfish.sh
        container: qc.uni_paltry-ruby-bordeaux
  QC.Ver:
    repos:
      github.com/mCodingLLC/SlapThatLikeButton-TestingStarterProject get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-carmine-reindeer.sh
        container: qc.ver_lovely-cobalt-koala
timeout: 5400
