config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui:
      branch: main
      repo: https://codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-jade-tetra.sh
        container: qc.acc_cranky-chestnut-flamingo
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-charcoal-javanese.sh
        container: qc.doc_paltry-taupe-terrier
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-blue-frise.sh
        container: qc.doc_tasty-wheat-robin
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cerise-axolotl.sh
        container: qc.lic_leaky-jade-caracal
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/ai/mlflow-auth-gui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-lavender-chipmunk.sh
        container: qc.ver_foggy-blue-dragonfly
timeout: 5400
