config:
  credentials: []
  project_repos:
    github.com/CERN-IT-INNOVATION/3DGAN:
      branch: main
      repo: https://github.com/CERN-IT-INNOVATION/3DGAN/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/CERN-IT-INNOVATION/3DGAN git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-goldenrod-paradise.sh
        container: qc.acc_stealthy-cornflower-caracal
  QC.Doc:
    repos:
      github.com/CERN-IT-INNOVATION/3DGAN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-cardinal-barb.sh
        container: qc.doc_shabby-ochre-chameleon
      github.com/CERN-IT-INNOVATION/3DGAN git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-chocolate-fousek.sh
        container: qc.doc_paltry-linen-eel
      github.com/CERN-IT-INNOVATION/3DGAN markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-lilac-chow.sh
        container: qc.doc_pokey-sapphire-jaguar
      github.com/CERN-IT-INNOVATION/3DGAN restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-crimson-gecko.sh
        container: qc.doc_craggy-heliotrope-fowl
  QC.Lic:
    repos:
      github.com/CERN-IT-INNOVATION/3DGAN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-asparagus-labradoodle.sh
        container: qc.lic_woolly-indigo-walrus
  QC.Sec:
    repos:
      github.com/CERN-IT-INNOVATION/3DGAN bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-saffron-corgi.sh
        container: qc.sec_homey-cobalt-rhinoceros
  QC.Sty:
    repos:
      github.com/CERN-IT-INNOVATION/3DGAN flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-yellow-foxhound.sh
        container: qc.sty_wimpy-chartreuse-goat
  QC.Uni:
    repos:
      github.com/CERN-IT-INNOVATION/3DGAN pytest:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-rust-cassowary.sh
        container: qc.uni_queasy-cobalt-mandrill
  QC.Ver:
    repos:
      github.com/CERN-IT-INNOVATION/3DGAN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-buff-koala.sh
        container: qc.ver_snoopy-ruby-magpie
timeout: 5400
